config/routes.rb
Rails.application.routes.draw do
  get 'products/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'products#index'
  resources :products, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :product
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    validates :title, presence: true
    validates :price, presence: true
    validates :stock_quantity, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.includes(:category).all
  end
  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>All Products:</h1>

<table>
    <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Price</th>
          <th>Stock Quantity</th>
          <th>Category</th>
        </tr>
    </thead>
    <tbody>
        <% @products.each do |product| %>
            <tr>
                <td><%= link_to product.title, product_path(product) %></td>
                <td><%= product.description %></td>
                <td><%= product.price %></td>
                <td style="text-align: right;"><%= product.stock_quantity %></td>
                <td style="text-align: right;"><%= product.category.name %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>
<p>Description: <%= @product.description %></p>
<p>Price: <%= number_to_currency(@product.price) %></p>
<p>Stock Quantity: <%= @product.stock_quantity %></p>
<p>Category: <%= @product.category.name %></p>